In [1]:
import numpy as np

# Умножение мтариц

In [2]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [3]:
A@x

array([26, 30])

In [4]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [19]:
def matrix_pr(a, b):
    try:
        result = a@b
        return result
    except ValueError as e:
        print("Ошибка: Матрица не может умножиться а в таком порядке")
    return b@a
    

In [20]:
matrix_pr(A,B)

Ошибка: Матрица не может умножиться а в таком порядке


array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

# Деление матриц

In [22]:
A = np.matrix('1,2; 2, 5')
A

matrix([[1, 2],
        [2, 5]])

In [23]:
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

# Практика

In [24]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [25]:
np.linalg.matrix_rank(A)

3

In [26]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [27]:
# Векторы
u1 = [-1, 2, -7, 9]
v2 = [2, 8, 2, -1]

# Вычисление скалярного произведения
scalar_product = sum(u1[i]*v2[i] for i in range(len(u1)))
print("Скалярное произведение векторов:", scalar_product)

Скалярное произведение векторов: -9
